version: "3.7"

services:
  api:
    build: ../../                                          # or use image: name_your_image
    container_name: CleanArchitectureTemplate-api
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - '5000:5000'
    networks:
      - CleanArchitectureTemplate

  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=root                                 # set your container root username
      - POSTGRES_PASSWORD=secret                           # set your container root password
      - POSTGRES_DB=CleanArchitectureTemplate-docker       # set your container database name
    ports:
      - 5432:5432
    networks:
      - CleanArchitectureTemplate
    volumes:
      - postgres:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com              # set your container default email
      - PGADMIN_DEFAULT_PASSWORD=secret                    # set your container default password
    ports:
      - 5050:80
    networks:
      - CleanArchitectureTemplate
    volumes:
      - pgadmin:/var/lib/pgadmin

networks:
  CleanArchitectureTemplate:
    name: CleanArchitectureTemplate-network

volumes:
  postgres:
    driver: local
  pgadmin:
    driver: local