version: "3.7"

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=root                                 # set your container root username
      - POSTGRES_PASSWORD=secret                           # set your container root password
      - POSTGRES_DB=Malpa025-docker       # set your container database name
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com              # set your container default email
      - PGADMIN_DEFAULT_PASSWORD=secret                    # set your container default password
    ports:
      - 5050:80
    volumes:
      - pgadmin:/var/lib/pgadmin

networks:
  Malpa025:
    name: Malpa025-network

volumes:
  postgres:
    driver: local
  pgadmin:
    driver: local